app:
  ui-path: /ui
  keycloak:
    realm: ${KEYCLOAK_REALM}
    auth-server-url: ${FRONTEND_AUTH_SERVER_URL}
    ssl-require: none
    resource: ${KEYCLOAK_RESOURCE}
    public-client: true
    cors: true

tesler:
  bean:
    multipart-resolver:
      enabled: false
  meta:
    dev-panel-enabled: ${DEV_PANEL_ENABLED:false}
    directory: ${META_DIRECTORY:file:./src/main/resources/meta}
    view-allowed-roles-enabled: true
  widget:
    fields:
      include-packages:
        - io.tesler.core.ui.model.json.field.subtypes
        - ru.filit.notifications.conf.tesler.meta
  api:
    path: /api/v1
    use-servlet-context-path: false
  ui:
    path: /ui
    use-servlet-context-path: false

server:
  port : ${SERVER_PORT:8080}
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        http-only: true

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
  datasource:
    name: primaryDS
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: classpath:/db/db.changelog-master.xml
    drop-first: ${LIQUIBASE_DROP_FIRST:false}
  cache:
    type: None
  jpa:
    properties:
      hibernate:
        synonyms: true
        default_batch_fetch_size: 100
        order_updates: true
        order_inserts: true
        batch_versioned_data: true
        batch_fetch_style: DYNAMIC
        criteria:
          literal_handling_mode: BIND
        connection:
          includeSynonyms: true
          charSet: UTF-8
        jdbc:
          batch_size: 100
    hibernate:
      naming:
        physical-strategy: io.tesler.model.core.hbn.ImprovedPhysicalNamingStrategy
  main:
    allow-bean-definition-overriding: true

keycloak:
  auth-server-url: ${BACKEND_AUTH_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_RESOURCE}
  bearer-only: true
  public-client: true
  use-resource-role-mappings: true
  ssl-required: none
